
# POST http://localhost:7000/philomena/interactions/likeUnlikeComments HTTP/1.1
# content-type: application/json

# {
#     "commentID": "6404a65353273e1bfe4f8761",
#     "likedBy": "anne"
# }

# GET http://localhost:7000/philomena/posts/getPostComments/6404a57bc5ad56fefabdc9cb

# POST http://localhost:7000/philomena/interactions/commentOnPost HTTP/1.1
# content-type: application/json

# {
#     "fullname": "Dagmawi Babi",
#     "username": "dagmawibabi",
#     "postID": "6404a57bc5ad56fefabdc9cb",
#     "content": "It's so cool right?!!"
# }

# GET http://localhost:7000/philomena/community/getCommunityMembers/dbcommunity
# GET http://localhost:7000/philomena/community/getCommunityMembers/dagmawibabi
# GET http://localhost:7000/philomena/community/deleteCommunity/SamAltmanCommunity/dagmawibabi
# GET http://localhost:7000/philomena/community/getMyCommunities/dagmawibabi
# GET http://localhost:7000/philomena/community/getCommunityChat/SamAltmanCommunity
# GET http://localhost:7000/philomena/community/clearCommunityChat/SamAltmanCommunity/dagmawibabi
# GET http://localhost:7000/philomena/community/clearAllCommunityChat/SamAltmanCommunity

# POST http://localhost:7000/philomena/community/sendCommunityChat HTTP/1.1
# content-type: application/json

# {
#     "from": "dagmawibabixx",
#     "community": "SamAltmanCommunity",
#     "forwardedFrom": "",
#     "content": "bruh"
# }

# POST http://localhost:7000/philomena/community/createCommunity HTTP/1.1
# content-type: application/json

# {
#     "name": "Dagmawi Babi",
#     "username": "dbcommunity",
#     "members": "",
#     "bio": "Welcome to my community",
#     "private": false,
#     "owner": "dagmawibabi"
# }


# GET http://localhost:7000/philomena/community/leaveCommunity/SamAltmanCommunity/dagmawibabi
# GET http://localhost:7000/philomena/community/joinCommunity/dbcommunity/anne
# GET http://localhost:7000/philomena/community


# GET http://localhost:7000/philomena/bots


# GET http://localhost:7000/philomena/privateChats/clearPrivateChat/dagmAwibabi/anne

# GET http://localhost:7000/philomena/privateChats/getChats/dagmawibabi


# GET http://localhost:7000/philomena/posts/getFeed/anne

# GET http://localhost:7000/philomena/interactions/followUnfollowuser/anne/dagmawibabi

# GET http://localhost:7000/philomena/profile/getAllFollowers/dagmawibabi
# GET http://localhost:7000/philomena/profile/getAllFollowing/dagmawibabi

# GET http://localhost:7000/philomena/privateChats/getPrivateChat/anne/dagmawibabi

# POST http://localhost:7000/philomena/privateChats/sendPrivateMessage HTTP/1.1
# content-type: application/json

# {
#     "from": "anne",
#     "to": "dagmawibabi",
#     "forwardedFrom": "",
#     "content": "broooo yooo"
# }

# GET http://localhost:7000/philomena/privateChats/

# POST http://localhost:7000/philomena/upload/images HTTP/1.1
# content-type: application/json

# {
#     "username": "dagmawibabi",
#     "content": "\\",
#     "time": "1673389885558"
# }


# GET http://localhost:7000/philomena/upload/images

# GET http://localhost:7000/philomena/profile/getprofile/dagmawibabi

# POST http://localhost:7000/philomena/posts/deletePost HTTP/1.1
# content-type: application/json

# {
#     "username": "dagmawibabi",
#     "content": "\\",
#     "time": "1673389885558"
# }

# POST http://localhost:7000/philomena/posts/newPost HTTP/1.1
# content-type: application/json

# {
#     "fullname": "Dagmawi Babi",
#     "username": "dagmawibabi",
#     "content": "I'm on Philomena"
# }

# GET http://localhost:7000/philomena/search/
# GET http://localhost:7000/philomena/search/doe

# GET http://localhost:7000/philomena/notifications/
# GET http://localhost:7000/philomena/authentication/

# POST http://localhost:7000/philomena/notifications/readNotifications HTTP/1.1
# content-type: application/json

# {
#     "notificationID": "63a8cf6bb12b98128e7529bf"
# }

# POST http://localhost:7000/philomena/notifications/getNotifications HTTP/1.1
# content-type: application/json

# {
#     "username": "dagmawibabi"
# }

# POST http://localhost:7000/philomena/interactions/likeDislikePosts HTTP/1.1
# content-type: application/json

# {
#     "postID": "639ee0c1d37e8a5ba969fd0d",
#     "likedBy": "devOne"
# }

# POST http://localhost:7000/philomena/authentication/signup HTTP/1.1
# content-type: application/json

# {
#     "fullname": "Anne Leone",
#     "username": "anne",
#     "password": "anne"
# }

# "fullname": "Dagmawi Babi",
# "username": "dagmawibabi",
# "password": "dagmawibabi"

# POST http://localhost:7000/philomena/authentication/login HTTP/1.1
# content-type: application/json

# {
#     "username": "papi",
#     "password": "babi"
# }

// https://dagmawibabi.com/static/media/me.b4b941897136a2959e33.png
// https://equatemagazine.com/wp-content/uploads/2021/06/Anna_MVinay014D-small-crop-scaled.jpg