GET http://localhost:7000/philomena/privateChats/getPrivateChat/dagmAwibabi/jordanb

# POST http://localhost:7000/philomena/privateChats/sendPrivateMessage HTTP/1.1
# content-type: application/json

# {
#     "from": "jordanb",
#     "to": "dagmawiBabi",
#     "forwardedFrom": "",
#     "content": "aig afa a ascadia iagd i"
# }

# GET http://localhost:7000/philomena/privateChats/

# POST http://localhost:7000/philomena/upload/images HTTP/1.1
# content-type: application/json

# {
#     "username": "dagmawibabi",
#     "content": "\\",
#     "time": "1673389885558"
# }


# GET http://localhost:7000/philomena/upload/images

# GET http://localhost:7000/philomena/profile/getprofile/dagmawibabi

# POST http://localhost:7000/philomena/posts/deletePost HTTP/1.1
# content-type: application/json

# {
#     "username": "dagmawibabi",
#     "content": "\\",
#     "time": "1673389885558"
# }


# GET http://localhost:7000/philomena/search/
# GET http://localhost:7000/philomena/search/doe

# GET http://localhost:7000/philomena/notifications/
# GET http://localhost:7000/philomena/authentication/

# POST http://localhost:7000/philomena/notifications/readNotifications HTTP/1.1
# content-type: application/json

# {
#     "notificationID": "63a8cf6bb12b98128e7529bf"
# }

# POST http://localhost:7000/philomena/notifications/getNotifications HTTP/1.1
# content-type: application/json

# {
#     "username": "dagmawibabi"
# }

# POST http://localhost:7000/philomena/interactions/likeDislikePosts HTTP/1.1
# content-type: application/json

# {
#     "postID": "639ee0c1d37e8a5ba969fd0d",
#     "likedBy": "devOne"
# }

# POST http://localhost:7000/philomena/authentication/signup HTTP/1.1
# content-type: application/json

# {
#     "fullname": "papm",
#     "username": "papixx",
#     "password": "babi"
# }

# POST http://localhost:7000/philomena/authentication/login HTTP/1.1
# content-type: application/json

# {
#     "username": "papi",
#     "password": "babi"
# }
